/* soapBasicHttpBinding_USCOREDonatPismenaServiceContractProxy.h
   Generated by gSOAP 2.8.17r from DonatPismenaService.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBasicHttpBinding_USCOREDonatPismenaServiceContractProxy_H
#define soapBasicHttpBinding_USCOREDonatPismenaServiceContractProxy_H
#include "soapH.h"

class SOAP_CMAC BasicHttpBinding_USCOREDonatPismenaServiceContractProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREDonatPismenaServiceContractProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BasicHttpBinding_USCOREDonatPismenaServiceContractProxy();
	/// Constructor to use/share an engine state
	BasicHttpBinding_USCOREDonatPismenaServiceContractProxy(struct soap*);
	/// Constructor with endpoint URL
	BasicHttpBinding_USCOREDonatPismenaServiceContractProxy(const char *url);
	/// Constructor with engine input+output mode control
	BasicHttpBinding_USCOREDonatPismenaServiceContractProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BasicHttpBinding_USCOREDonatPismenaServiceContractProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BasicHttpBinding_USCOREDonatPismenaServiceContractProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BasicHttpBinding_USCOREDonatPismenaServiceContractProxy();
	/// Initializer used by constructors
	virtual	void BasicHttpBinding_USCOREDonatPismenaServiceContractProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetZahtjevPdf' (returns error code or SOAP_OK)
	virtual	int GetZahtjevPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatZahtjevReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetZahtjevPdf(NULL, NULL, ns1__DonatZahtjevReq, ns1__PdfResponse); }
	virtual	int GetZahtjevPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatZahtjevReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetZahtjev' (returns error code or SOAP_OK)
	virtual	int GetZahtjev(ns2__DonatPismenoRequestDataContract *ns1__DonatZahtjevReq, ns2__DonatPismenoDataContract *ns1__ZahtjevResponse) { return this->GetZahtjev(NULL, NULL, ns1__DonatZahtjevReq, ns1__ZahtjevResponse); }
	virtual	int GetZahtjev(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatZahtjevReq, ns2__DonatPismenoDataContract *ns1__ZahtjevResponse);

	/// Web service operation 'GetUgovorPdf' (returns error code or SOAP_OK)
	virtual	int GetUgovorPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatUgovorReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetUgovorPdf(NULL, NULL, ns1__DonatUgovorReq, ns1__PdfResponse); }
	virtual	int GetUgovorPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatUgovorReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetUgovor' (returns error code or SOAP_OK)
	virtual	int GetUgovor(ns2__DonatPismenoRequestDataContract *ns1__DonatUgovorReq, ns2__DonatPismenoDataContract *ns1__UgovorResponse) { return this->GetUgovor(NULL, NULL, ns1__DonatUgovorReq, ns1__UgovorResponse); }
	virtual	int GetUgovor(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatUgovorReq, ns2__DonatPismenoDataContract *ns1__UgovorResponse);

	/// Web service operation 'GetPrivolaPdf' (returns error code or SOAP_OK)
	virtual	int GetPrivolaPdf(LONG64 ns1__KupacId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetPrivolaPdf(NULL, NULL, ns1__KupacId, ns1__PdfResponse); }
	virtual	int GetPrivolaPdf(const char *endpoint, const char *soap_action, LONG64 ns1__KupacId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetPrivola' (returns error code or SOAP_OK)
	virtual	int GetPrivola(LONG64 ns1__KupacId, ns2__DonatPismenoDataContract *ns1__PrivolaResponse) { return this->GetPrivola(NULL, NULL, ns1__KupacId, ns1__PrivolaResponse); }
	virtual	int GetPrivola(const char *endpoint, const char *soap_action, LONG64 ns1__KupacId, ns2__DonatPismenoDataContract *ns1__PrivolaResponse);

	/// Web service operation 'GetObavijestPdf' (returns error code or SOAP_OK)
	virtual	int GetObavijestPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatObavijestReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetObavijestPdf(NULL, NULL, ns1__DonatObavijestReq, ns1__PdfResponse); }
	virtual	int GetObavijestPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatObavijestReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetObavijest' (returns error code or SOAP_OK)
	virtual	int GetObavijest(ns2__DonatPismenoRequestDataContract *ns1__DonatObavijestReq, ns2__DonatPismenoDataContract *ns1__ObavijestResponse) { return this->GetObavijest(NULL, NULL, ns1__DonatObavijestReq, ns1__ObavijestResponse); }
	virtual	int GetObavijest(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatObavijestReq, ns2__DonatPismenoDataContract *ns1__ObavijestResponse);

	/// Web service operation 'GetPismoPdf' (returns error code or SOAP_OK)
	virtual	int GetPismoPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatPismoReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetPismoPdf(NULL, NULL, ns1__DonatPismoReq, ns1__PdfResponse); }
	virtual	int GetPismoPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatPismoReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetPismo' (returns error code or SOAP_OK)
	virtual	int GetPismo(ns2__DonatPismenoRequestDataContract *ns1__DonatPismoReq, ns2__DonatPismenoDataContract *ns1__PismoResponse) { return this->GetPismo(NULL, NULL, ns1__DonatPismoReq, ns1__PismoResponse); }
	virtual	int GetPismo(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatPismoReq, ns2__DonatPismenoDataContract *ns1__PismoResponse);

	/// Web service operation 'GetOdbijenicaPdf' (returns error code or SOAP_OK)
	virtual	int GetOdbijenicaPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatOdbijenicaReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetOdbijenicaPdf(NULL, NULL, ns1__DonatOdbijenicaReq, ns1__PdfResponse); }
	virtual	int GetOdbijenicaPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatOdbijenicaReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetOdbijenica' (returns error code or SOAP_OK)
	virtual	int GetOdbijenica(ns2__DonatPismenoRequestDataContract *ns1__DonatOdbijenicaReq, ns2__DonatPismenoDataContract *ns1__OdbijenicaResponse) { return this->GetOdbijenica(NULL, NULL, ns1__DonatOdbijenicaReq, ns1__OdbijenicaResponse); }
	virtual	int GetOdbijenica(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatOdbijenicaReq, ns2__DonatPismenoDataContract *ns1__OdbijenicaResponse);

	/// Web service operation 'GetUgovornaObvezaPdf' (returns error code or SOAP_OK)
	virtual	int GetUgovornaObvezaPdf(LONG64 ns1__GrupaImovineId, LONG64 ns1__KupacId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetUgovornaObvezaPdf(NULL, NULL, ns1__GrupaImovineId, ns1__KupacId, ns1__PdfResponse); }
	virtual	int GetUgovornaObvezaPdf(const char *endpoint, const char *soap_action, LONG64 ns1__GrupaImovineId, LONG64 ns1__KupacId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetUgovornaObveza' (returns error code or SOAP_OK)
	virtual	int GetUgovornaObveza(LONG64 ns1__GrupaImovineId, LONG64 ns1__KupacId, ns2__DonatPismenoDataContract *ns1__UgovornaObvezaResponse) { return this->GetUgovornaObveza(NULL, NULL, ns1__GrupaImovineId, ns1__KupacId, ns1__UgovornaObvezaResponse); }
	virtual	int GetUgovornaObveza(const char *endpoint, const char *soap_action, LONG64 ns1__GrupaImovineId, LONG64 ns1__KupacId, ns2__DonatPismenoDataContract *ns1__UgovornaObvezaResponse);

	/// Web service operation 'GetTrajniNalogPdf' (returns error code or SOAP_OK)
	virtual	int GetTrajniNalogPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatTrajniNalogReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetTrajniNalogPdf(NULL, NULL, ns1__DonatTrajniNalogReq, ns1__PdfResponse); }
	virtual	int GetTrajniNalogPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatTrajniNalogReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetTrajniNalog' (returns error code or SOAP_OK)
	virtual	int GetTrajniNalog(ns2__DonatPismenoRequestDataContract *ns1__DonatTrajniNalogReq, ns2__DonatPismenoDataContract *ns1__TrajniNalogResponse) { return this->GetTrajniNalog(NULL, NULL, ns1__DonatTrajniNalogReq, ns1__TrajniNalogResponse); }
	virtual	int GetTrajniNalog(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatTrajniNalogReq, ns2__DonatPismenoDataContract *ns1__TrajniNalogResponse);

	/// Web service operation 'GetSplitContractPdf' (returns error code or SOAP_OK)
	virtual	int GetSplitContractPdf(ns2__DonatPismenoRequestDataContract *ns1__DonatSplitContractReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetSplitContractPdf(NULL, NULL, ns1__DonatSplitContractReq, ns1__PdfResponse); }
	virtual	int GetSplitContractPdf(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatSplitContractReq, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetSplitContract' (returns error code or SOAP_OK)
	virtual	int GetSplitContract(ns2__DonatPismenoRequestDataContract *ns1__DonatSplitContractReq, ns2__DonatPismenoDataContract *ns1__SplitContractResponse) { return this->GetSplitContract(NULL, NULL, ns1__DonatSplitContractReq, ns1__SplitContractResponse); }
	virtual	int GetSplitContract(const char *endpoint, const char *soap_action, ns2__DonatPismenoRequestDataContract *ns1__DonatSplitContractReq, ns2__DonatPismenoDataContract *ns1__SplitContractResponse);

	/// Web service operation 'GetZlonamjerniPdf' (returns error code or SOAP_OK)
	virtual	int GetZlonamjerniPdf(LONG64 ns1__ZlonamjerniId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetZlonamjerniPdf(NULL, NULL, ns1__ZlonamjerniId, ns1__PdfResponse); }
	virtual	int GetZlonamjerniPdf(const char *endpoint, const char *soap_action, LONG64 ns1__ZlonamjerniId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetZlonamjerni' (returns error code or SOAP_OK)
	virtual	int GetZlonamjerni(LONG64 ns1__ZlonamjerniId, ns2__DonatPismenoDataContract *ns1__ZlonamjerniResponse) { return this->GetZlonamjerni(NULL, NULL, ns1__ZlonamjerniId, ns1__ZlonamjerniResponse); }
	virtual	int GetZlonamjerni(const char *endpoint, const char *soap_action, LONG64 ns1__ZlonamjerniId, ns2__DonatPismenoDataContract *ns1__ZlonamjerniResponse);

	/// Web service operation 'GetPrigovorPdf' (returns error code or SOAP_OK)
	virtual	int GetPrigovorPdf(LONG64 ns1__PrigovorId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse) { return this->GetPrigovorPdf(NULL, NULL, ns1__PrigovorId, ns1__PdfResponse); }
	virtual	int GetPrigovorPdf(const char *endpoint, const char *soap_action, LONG64 ns1__PrigovorId, ns2__DonatPismenoPdfDataContract *ns1__PdfResponse);

	/// Web service operation 'GetPrigovor' (returns error code or SOAP_OK)
	virtual	int GetPrigovor(LONG64 ns1__PrigovorId, ns2__DonatPismenoDataContract *ns1__PrigovorResponse) { return this->GetPrigovor(NULL, NULL, ns1__PrigovorId, ns1__PrigovorResponse); }
	virtual	int GetPrigovor(const char *endpoint, const char *soap_action, LONG64 ns1__PrigovorId, ns2__DonatPismenoDataContract *ns1__PrigovorResponse);
};
#endif
